create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  name text not null,
  username text not null unique,
  password text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  lastname text not null,
  firstname text not null,
  middlename text default '',
  username text not null unique,
  password text not null,
  year_section text default '2-A',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  subject_name text not null unique
);

create table if not exists public.attendance_sessions (
  id bigint generated by default as identity primary key,
  subject_id bigint,
  qr_token text,
  session_id text not null unique,
  date text,
  expiration_time text,
  created_by text,
  created_at timestamptz default now()
);

create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  session_id text not null,
  student_id bigint not null,
  subject_id bigint,
  date text,
  time text,
  status text default 'Present',
  year_section text,
  student_name text,
  created_at timestamptz default now()
);

insert into public.teachers (name, username, password)
values ('Teacher Sijey', '@dm!n_cj', '$2a$10$OJzlPB0h7hu0kPZIYUnpueSquULESLwMZ6fAfpkVPdgu9sXCmAq1G')
on conflict (username) do nothing;

insert into public.subjects (subject_name)
values
  ('Information Assurance and Security 1'),
  ('Information Assurance and Security 2'),
  ('Information Management'),
  ('Web Systems and Technologies')
on conflict (subject_name) do nothing;
